import { createContext, useContext, useState, useEffect } from "react";

// Translations for all supported languages
const translations = {
  en: {
    // Navigation
    nav: {
      dashboard: "Dashboard",
      holdings: "Holdings",
      watchlist: "Watchlist",
      crypto: "Crypto",
      alerts: "Alerts",
      logout: "Logout",
      settings: "Settings",
    },
    // Dashboard
    dashboard: {
      title: "Dashboard",
      subtitle: "Your complete portfolio at a glance",
      totalPortfolio: "Total Portfolio",
      stocks: "Stocks",
      crypto: "Crypto",
      totalGainLoss: "Total Gain/Loss",
      allTime: "all time",
      holdings: "holdings",
      cost: "Cost",
      portfolioPerformance: "Portfolio Performance",
      allocation: "Allocation",
      noHoldingsYet: "No holdings yet",
      addStocksOrCrypto: "Add stocks or crypto to see your portfolio performance",
      addStock: "Add Stock",
      addCrypto: "Add Crypto",
      addHoldingsToSeeAllocation: "Add holdings to see allocation",
      stockHoldings: "Stock Holdings",
      cryptoHoldings: "Crypto Holdings",
      viewAll: "View All",
      shares: "shares",
      units: "units",
      noStockHoldings: "No stock holdings",
      noCryptoHoldings: "No crypto holdings",
      addStocks: "Add stocks",
      refresh: "Refresh",
    },
    // Holdings
    holdings: {
      title: "Holdings",
      subtitle: "Manage your stock portfolio",
      addHolding: "Add Holding",
      editHolding: "Edit Holding",
      addNewStock: "Add a new stock to your portfolio",
      updateDetails: "Update your holding details",
      stockSymbol: "Stock Symbol",
      shares: "Shares",
      buyPrice: "Buy Price",
      buyDate: "Buy Date (optional)",
      cancel: "Cancel",
      save: "Save",
      update: "Update",
      add: "Add",
      saving: "Saving...",
      noHoldingsYet: "No holdings yet",
      startBuilding: "Start building your portfolio by adding your first stock holding.",
      addFirstHolding: "Add Your First Holding",
      currentPrice: "Current Price",
      marketValue: "Market Value",
      gainLoss: "Gain/Loss",
      edit: "Edit",
      delete: "Delete",
    },
    // Watchlist
    watchlist: {
      title: "Watchlist",
      subtitle: "Track stocks you're interested in",
      addStock: "Add Stock",
      addToWatchlist: "Add to Watchlist",
      searchAndAdd: "Search and add a stock to track its price",
      cancel: "Cancel",
      add: "Add",
      adding: "Adding...",
      emptyTitle: "Your watchlist is empty",
      emptyDescription: "Add stocks to your watchlist to track their prices without owning them.",
      addFirstStock: "Add Your First Stock",
      addedOn: "Added",
      volume: "Vol",
    },
    // Crypto
    crypto: {
      title: "Crypto",
      subtitle: "Track your cryptocurrency portfolio",
      refresh: "Refresh",
      cryptoValue: "Crypto Value",
      gainLoss: "Gain/Loss",
      holdings: "Holdings",
      watching: "Watching",
      cryptocurrencies: "cryptocurrencies",
      inWatchlist: "in watchlist",
      holdingsTab: "Holdings",
      watchlistTab: "Watchlist",
      marketTab: "Market",
      addHolding: "Add Holding",
      addCryptoHolding: "Add Crypto Holding",
      editCryptoHolding: "Edit Crypto Holding",
      searchAndAdd: "Search and add a cryptocurrency",
      updateDetails: "Update your holding details",
      cryptocurrency: "Cryptocurrency",
      amount: "Amount",
      buyPriceUSD: "Buy Price (USD)",
      buyDate: "Buy Date (optional)",
      cancel: "Cancel",
      save: "Save",
      update: "Update",
      add: "Add",
      saving: "Saving...",
      noCryptoHoldings: "No crypto holdings yet",
      startTracking: "Start tracking your crypto portfolio by adding your first holding.",
      addFirstCrypto: "Add Your First Crypto",
      currentPrice: "Current Price",
      marketValue: "Market Value",
      edit: "Edit",
      delete: "Delete",
      addToWatchlist: "Add to Watchlist",
      searchCrypto: "Search and add a cryptocurrency to track",
      emptyWatchlist: "Watchlist is empty",
      emptyWatchlistDesc: "Add cryptocurrencies to your watchlist to track their prices.",
      topCryptocurrencies: "Top Cryptocurrencies",
      price: "Price",
      change24h: "24h",
      marketCap: "Market Cap",
    },
    // Alerts
    alerts: {
      title: "Price Alerts",
      subtitle: "Get notified when prices hit your targets",
      enableNotifications: "Enable Notifications",
      checkNow: "Check Now",
      createAlert: "Create Alert",
      notificationsEnabled: "Browser notifications enabled - you'll be alerted when prices hit your targets",
      active: "Active",
      triggered: "Triggered",
      noActiveAlerts: "No active alerts",
      createAlertsDesc: "Create price alerts to get notified when stocks or crypto hit your target prices.",
      createFirstAlert: "Create Your First Alert",
      noTriggeredAlerts: "No triggered alerts",
      triggeredAlertsDesc: "When your price targets are hit, triggered alerts will appear here.",
      createPriceAlert: "Create Price Alert",
      getNotified: "Get notified when an asset hits your target price",
      assetType: "Asset Type",
      stock: "Stock",
      searchStock: "Search Stock",
      searchCrypto: "Search Cryptocurrency",
      condition: "Condition",
      priceAbove: "Price goes above",
      priceBelow: "Price goes below",
      targetPrice: "Target Price (USD)",
      cancel: "Cancel",
      create: "Create Alert",
      creating: "Creating...",
      target: "Target",
      priceAtTrigger: "Price at Trigger",
      currentPrice: "Current Price",
      resetAlert: "Reset alert",
      triggeredOn: "Triggered on",
      above: "Above",
      below: "Below",
    },
    // Auth
    auth: {
      welcomeBack: "Welcome back",
      signInToPortfolio: "Sign in to your portfolio",
      email: "Email",
      password: "Password",
      signIn: "Sign In",
      signingIn: "Signing in...",
      noAccount: "Don't have an account?",
      createAccount: "Create account",
      createAnAccount: "Create an account",
      startTracking: "Start tracking your investments today",
      name: "Name",
      creatingAccount: "Creating account...",
      alreadyHaveAccount: "Already have an account?",
      signInLink: "Sign in",
    },
    // Common
    common: {
      loading: "Loading...",
      error: "Error",
      success: "Success",
      search: "Search",
      save: "Save",
      cancel: "Cancel",
      delete: "Delete",
      edit: "Edit",
      add: "Add",
      remove: "Remove",
      confirm: "Confirm",
      close: "Close",
      yes: "Yes",
      no: "No",
    },
    // Settings
    settings: {
      title: "Settings",
      subtitle: "Manage your application preferences",
      languageTitle: "Language",
      languageDescription: "Choose your preferred language for the application",
    },
  },
  fr: {
    // Navigation
    nav: {
      dashboard: "Tableau de bord",
      holdings: "Portefeuille",
      watchlist: "Liste de suivi",
      crypto: "Crypto",
      alerts: "Alertes",
      logout: "Déconnexion",
      settings: "Paramètres",
    },
    // Dashboard
    dashboard: {
      title: "Tableau de bord",
      subtitle: "Votre portefeuille complet en un coup d'œil",
      totalPortfolio: "Portefeuille Total",
      stocks: "Actions",
      crypto: "Crypto",
      totalGainLoss: "Gain/Perte Total",
      allTime: "depuis le début",
      holdings: "positions",
      cost: "Coût",
      portfolioPerformance: "Performance du Portefeuille",
      allocation: "Répartition",
      noHoldingsYet: "Pas encore de positions",
      addStocksOrCrypto: "Ajoutez des actions ou des cryptos pour voir la performance",
      addStock: "Ajouter une Action",
      addCrypto: "Ajouter une Crypto",
      addHoldingsToSeeAllocation: "Ajoutez des positions pour voir la répartition",
      stockHoldings: "Actions en Portefeuille",
      cryptoHoldings: "Cryptos en Portefeuille",
      viewAll: "Voir Tout",
      shares: "actions",
      units: "unités",
      noStockHoldings: "Aucune action",
      noCryptoHoldings: "Aucune crypto",
      addStocks: "Ajouter des actions",
      refresh: "Actualiser",
    },
    // Holdings
    holdings: {
      title: "Portefeuille",
      subtitle: "Gérez votre portefeuille d'actions",
      addHolding: "Ajouter une Position",
      editHolding: "Modifier la Position",
      addNewStock: "Ajouter une nouvelle action à votre portefeuille",
      updateDetails: "Mettre à jour les détails de votre position",
      stockSymbol: "Symbole de l'Action",
      shares: "Actions",
      buyPrice: "Prix d'Achat",
      buyDate: "Date d'Achat (optionnel)",
      cancel: "Annuler",
      save: "Enregistrer",
      update: "Mettre à jour",
      add: "Ajouter",
      saving: "Enregistrement...",
      noHoldingsYet: "Pas encore de positions",
      startBuilding: "Commencez à construire votre portefeuille en ajoutant votre première action.",
      addFirstHolding: "Ajouter Votre Première Position",
      currentPrice: "Prix Actuel",
      marketValue: "Valeur de Marché",
      gainLoss: "Gain/Perte",
      edit: "Modifier",
      delete: "Supprimer",
    },
    // Watchlist
    watchlist: {
      title: "Liste de Suivi",
      subtitle: "Suivez les actions qui vous intéressent",
      addStock: "Ajouter une Action",
      addToWatchlist: "Ajouter à la Liste",
      searchAndAdd: "Recherchez et ajoutez une action à suivre",
      cancel: "Annuler",
      add: "Ajouter",
      adding: "Ajout...",
      emptyTitle: "Votre liste de suivi est vide",
      emptyDescription: "Ajoutez des actions à votre liste pour suivre leurs prix sans les posséder.",
      addFirstStock: "Ajouter Votre Première Action",
      addedOn: "Ajouté le",
      volume: "Vol",
    },
    // Crypto
    crypto: {
      title: "Crypto",
      subtitle: "Suivez votre portefeuille de cryptomonnaies",
      refresh: "Actualiser",
      cryptoValue: "Valeur Crypto",
      gainLoss: "Gain/Perte",
      holdings: "Positions",
      watching: "Suivi",
      cryptocurrencies: "cryptomonnaies",
      inWatchlist: "en liste de suivi",
      holdingsTab: "Positions",
      watchlistTab: "Liste de Suivi",
      marketTab: "Marché",
      addHolding: "Ajouter une Position",
      addCryptoHolding: "Ajouter une Position Crypto",
      editCryptoHolding: "Modifier la Position Crypto",
      searchAndAdd: "Recherchez et ajoutez une cryptomonnaie",
      updateDetails: "Mettre à jour les détails de votre position",
      cryptocurrency: "Cryptomonnaie",
      amount: "Quantité",
      buyPriceUSD: "Prix d'Achat (USD)",
      buyDate: "Date d'Achat (optionnel)",
      cancel: "Annuler",
      save: "Enregistrer",
      update: "Mettre à jour",
      add: "Ajouter",
      saving: "Enregistrement...",
      noCryptoHoldings: "Pas encore de positions crypto",
      startTracking: "Commencez à suivre votre portefeuille crypto en ajoutant votre première position.",
      addFirstCrypto: "Ajouter Votre Première Crypto",
      currentPrice: "Prix Actuel",
      marketValue: "Valeur de Marché",
      edit: "Modifier",
      delete: "Supprimer",
      addToWatchlist: "Ajouter à la Liste",
      searchCrypto: "Recherchez une cryptomonnaie à suivre",
      emptyWatchlist: "Liste de suivi vide",
      emptyWatchlistDesc: "Ajoutez des cryptomonnaies à votre liste pour suivre leurs prix.",
      topCryptocurrencies: "Top Cryptomonnaies",
      price: "Prix",
      change24h: "24h",
      marketCap: "Cap. Marché",
    },
    // Alerts
    alerts: {
      title: "Alertes de Prix",
      subtitle: "Soyez notifié quand les prix atteignent vos objectifs",
      enableNotifications: "Activer les Notifications",
      checkNow: "Vérifier",
      createAlert: "Créer une Alerte",
      notificationsEnabled: "Notifications activées - vous serez alerté quand vos objectifs seront atteints",
      active: "Actives",
      triggered: "Déclenchées",
      noActiveAlerts: "Aucune alerte active",
      createAlertsDesc: "Créez des alertes pour être notifié quand les prix atteignent vos objectifs.",
      createFirstAlert: "Créer Votre Première Alerte",
      noTriggeredAlerts: "Aucune alerte déclenchée",
      triggeredAlertsDesc: "Les alertes déclenchées apparaîtront ici.",
      createPriceAlert: "Créer une Alerte de Prix",
      getNotified: "Soyez notifié quand un actif atteint votre prix cible",
      assetType: "Type d'Actif",
      stock: "Action",
      searchStock: "Rechercher une Action",
      searchCrypto: "Rechercher une Cryptomonnaie",
      condition: "Condition",
      priceAbove: "Prix supérieur à",
      priceBelow: "Prix inférieur à",
      targetPrice: "Prix Cible (USD)",
      cancel: "Annuler",
      create: "Créer l'Alerte",
      creating: "Création...",
      target: "Cible",
      priceAtTrigger: "Prix au Déclenchement",
      currentPrice: "Prix Actuel",
      resetAlert: "Réinitialiser",
      triggeredOn: "Déclenchée le",
      above: "Au-dessus",
      below: "En-dessous",
    },
    // Auth
    auth: {
      welcomeBack: "Bon retour",
      signInToPortfolio: "Connectez-vous à votre portefeuille",
      email: "Email",
      password: "Mot de passe",
      signIn: "Se Connecter",
      signingIn: "Connexion...",
      noAccount: "Pas encore de compte ?",
      createAccount: "Créer un compte",
      createAnAccount: "Créer un compte",
      startTracking: "Commencez à suivre vos investissements",
      name: "Nom",
      creatingAccount: "Création...",
      alreadyHaveAccount: "Déjà un compte ?",
      signInLink: "Se connecter",
    },
    // Common
    common: {
      loading: "Chargement...",
      error: "Erreur",
      success: "Succès",
      search: "Rechercher",
      save: "Enregistrer",
      cancel: "Annuler",
      delete: "Supprimer",
      edit: "Modifier",
      add: "Ajouter",
      remove: "Retirer",
      confirm: "Confirmer",
      close: "Fermer",
      yes: "Oui",
      no: "Non",
    },
    // Settings
    settings: {
      title: "Paramètres",
      subtitle: "Gérez vos préférences d'application",
      languageTitle: "Langue",
      languageDescription: "Choisissez votre langue préférée pour l'application",
    },
  },
  de: {
    // Navigation
    nav: {
      dashboard: "Dashboard",
      holdings: "Bestände",
      watchlist: "Beobachtungsliste",
      crypto: "Krypto",
      alerts: "Alarme",
      logout: "Abmelden",
      settings: "Einstellungen",
    },
    // Dashboard
    dashboard: {
      title: "Dashboard",
      subtitle: "Ihr komplettes Portfolio auf einen Blick",
      totalPortfolio: "Gesamtportfolio",
      stocks: "Aktien",
      crypto: "Krypto",
      totalGainLoss: "Gesamtgewinn/-verlust",
      allTime: "gesamt",
      holdings: "Positionen",
      cost: "Kosten",
      portfolioPerformance: "Portfolio-Performance",
      allocation: "Aufteilung",
      noHoldingsYet: "Noch keine Bestände",
      addStocksOrCrypto: "Fügen Sie Aktien oder Krypto hinzu, um Ihre Performance zu sehen",
      addStock: "Aktie Hinzufügen",
      addCrypto: "Krypto Hinzufügen",
      addHoldingsToSeeAllocation: "Fügen Sie Bestände hinzu, um die Aufteilung zu sehen",
      stockHoldings: "Aktienbestände",
      cryptoHoldings: "Kryptobestände",
      viewAll: "Alle Anzeigen",
      shares: "Aktien",
      units: "Einheiten",
      noStockHoldings: "Keine Aktien",
      noCryptoHoldings: "Keine Kryptos",
      addStocks: "Aktien hinzufügen",
      refresh: "Aktualisieren",
    },
    // Holdings
    holdings: {
      title: "Bestände",
      subtitle: "Verwalten Sie Ihr Aktienportfolio",
      addHolding: "Position Hinzufügen",
      editHolding: "Position Bearbeiten",
      addNewStock: "Eine neue Aktie zu Ihrem Portfolio hinzufügen",
      updateDetails: "Aktualisieren Sie Ihre Positionsdetails",
      stockSymbol: "Aktiensymbol",
      shares: "Aktien",
      buyPrice: "Kaufpreis",
      buyDate: "Kaufdatum (optional)",
      cancel: "Abbrechen",
      save: "Speichern",
      update: "Aktualisieren",
      add: "Hinzufügen",
      saving: "Speichern...",
      noHoldingsYet: "Noch keine Bestände",
      startBuilding: "Beginnen Sie mit dem Aufbau Ihres Portfolios.",
      addFirstHolding: "Erste Position Hinzufügen",
      currentPrice: "Aktueller Preis",
      marketValue: "Marktwert",
      gainLoss: "Gewinn/Verlust",
      edit: "Bearbeiten",
      delete: "Löschen",
    },
    // Watchlist
    watchlist: {
      title: "Beobachtungsliste",
      subtitle: "Verfolgen Sie interessante Aktien",
      addStock: "Aktie Hinzufügen",
      addToWatchlist: "Zur Liste Hinzufügen",
      searchAndAdd: "Suchen und fügen Sie eine Aktie hinzu",
      cancel: "Abbrechen",
      add: "Hinzufügen",
      adding: "Hinzufügen...",
      emptyTitle: "Ihre Beobachtungsliste ist leer",
      emptyDescription: "Fügen Sie Aktien hinzu, um deren Kurse zu verfolgen.",
      addFirstStock: "Erste Aktie Hinzufügen",
      addedOn: "Hinzugefügt am",
      volume: "Vol",
    },
    // Crypto
    crypto: {
      title: "Krypto",
      subtitle: "Verwalten Sie Ihr Krypto-Portfolio",
      refresh: "Aktualisieren",
      cryptoValue: "Krypto-Wert",
      gainLoss: "Gewinn/Verlust",
      holdings: "Bestände",
      watching: "Beobachtet",
      cryptocurrencies: "Kryptowährungen",
      inWatchlist: "in Beobachtungsliste",
      holdingsTab: "Bestände",
      watchlistTab: "Beobachtungsliste",
      marketTab: "Markt",
      addHolding: "Position Hinzufügen",
      addCryptoHolding: "Krypto-Position Hinzufügen",
      editCryptoHolding: "Krypto-Position Bearbeiten",
      searchAndAdd: "Suchen und fügen Sie eine Kryptowährung hinzu",
      updateDetails: "Aktualisieren Sie Ihre Positionsdetails",
      cryptocurrency: "Kryptowährung",
      amount: "Menge",
      buyPriceUSD: "Kaufpreis (USD)",
      buyDate: "Kaufdatum (optional)",
      cancel: "Abbrechen",
      save: "Speichern",
      update: "Aktualisieren",
      add: "Hinzufügen",
      saving: "Speichern...",
      noCryptoHoldings: "Noch keine Krypto-Bestände",
      startTracking: "Beginnen Sie mit der Verfolgung Ihres Krypto-Portfolios.",
      addFirstCrypto: "Erste Krypto Hinzufügen",
      currentPrice: "Aktueller Preis",
      marketValue: "Marktwert",
      edit: "Bearbeiten",
      delete: "Löschen",
      addToWatchlist: "Zur Liste Hinzufügen",
      searchCrypto: "Suchen Sie eine Kryptowährung zum Verfolgen",
      emptyWatchlist: "Beobachtungsliste leer",
      emptyWatchlistDesc: "Fügen Sie Kryptowährungen hinzu, um deren Kurse zu verfolgen.",
      topCryptocurrencies: "Top Kryptowährungen",
      price: "Preis",
      change24h: "24h",
      marketCap: "Marktkapitalisierung",
    },
    // Alerts
    alerts: {
      title: "Preisalarme",
      subtitle: "Werden Sie benachrichtigt, wenn Preise Ihre Ziele erreichen",
      enableNotifications: "Benachrichtigungen Aktivieren",
      checkNow: "Jetzt Prüfen",
      createAlert: "Alarm Erstellen",
      notificationsEnabled: "Benachrichtigungen aktiviert - Sie werden alarmiert, wenn Ihre Ziele erreicht werden",
      active: "Aktiv",
      triggered: "Ausgelöst",
      noActiveAlerts: "Keine aktiven Alarme",
      createAlertsDesc: "Erstellen Sie Alarme, um benachrichtigt zu werden.",
      createFirstAlert: "Ersten Alarm Erstellen",
      noTriggeredAlerts: "Keine ausgelösten Alarme",
      triggeredAlertsDesc: "Ausgelöste Alarme erscheinen hier.",
      createPriceAlert: "Preisalarm Erstellen",
      getNotified: "Werden Sie benachrichtigt, wenn ein Asset Ihren Zielpreis erreicht",
      assetType: "Asset-Typ",
      stock: "Aktie",
      searchStock: "Aktie Suchen",
      searchCrypto: "Kryptowährung Suchen",
      condition: "Bedingung",
      priceAbove: "Preis steigt über",
      priceBelow: "Preis fällt unter",
      targetPrice: "Zielpreis (USD)",
      cancel: "Abbrechen",
      create: "Alarm Erstellen",
      creating: "Erstellen...",
      target: "Ziel",
      priceAtTrigger: "Preis bei Auslösung",
      currentPrice: "Aktueller Preis",
      resetAlert: "Zurücksetzen",
      triggeredOn: "Ausgelöst am",
      above: "Über",
      below: "Unter",
    },
    // Auth
    auth: {
      welcomeBack: "Willkommen zurück",
      signInToPortfolio: "Melden Sie sich bei Ihrem Portfolio an",
      email: "E-Mail",
      password: "Passwort",
      signIn: "Anmelden",
      signingIn: "Anmelden...",
      noAccount: "Noch kein Konto?",
      createAccount: "Konto erstellen",
      createAnAccount: "Konto erstellen",
      startTracking: "Beginnen Sie mit der Verfolgung Ihrer Investitionen",
      name: "Name",
      creatingAccount: "Erstellen...",
      alreadyHaveAccount: "Bereits ein Konto?",
      signInLink: "Anmelden",
    },
    // Common
    common: {
      loading: "Laden...",
      error: "Fehler",
      success: "Erfolg",
      search: "Suchen",
      save: "Speichern",
      cancel: "Abbrechen",
      delete: "Löschen",
      edit: "Bearbeiten",
      add: "Hinzufügen",
      remove: "Entfernen",
      confirm: "Bestätigen",
      close: "Schließen",
      yes: "Ja",
      no: "Nein",
    },
    // Settings
    settings: {
      title: "Einstellungen",
      subtitle: "Verwalten Sie Ihre Anwendungseinstellungen",
      languageTitle: "Sprache",
      languageDescription: "Wählen Sie Ihre bevorzugte Sprache für die Anwendung",
    },
  },
  es: {
    // Navigation
    nav: {
      dashboard: "Panel",
      holdings: "Cartera",
      watchlist: "Seguimiento",
      crypto: "Cripto",
      alerts: "Alertas",
      logout: "Cerrar Sesión",
      settings: "Configuración",
    },
    // Dashboard
    dashboard: {
      title: "Panel",
      subtitle: "Tu cartera completa de un vistazo",
      totalPortfolio: "Cartera Total",
      stocks: "Acciones",
      crypto: "Cripto",
      totalGainLoss: "Ganancia/Pérdida Total",
      allTime: "histórico",
      holdings: "posiciones",
      cost: "Costo",
      portfolioPerformance: "Rendimiento de la Cartera",
      allocation: "Distribución",
      noHoldingsYet: "Sin posiciones aún",
      addStocksOrCrypto: "Añade acciones o cripto para ver tu rendimiento",
      addStock: "Añadir Acción",
      addCrypto: "Añadir Cripto",
      addHoldingsToSeeAllocation: "Añade posiciones para ver la distribución",
      stockHoldings: "Acciones en Cartera",
      cryptoHoldings: "Criptos en Cartera",
      viewAll: "Ver Todo",
      shares: "acciones",
      units: "unidades",
      noStockHoldings: "Sin acciones",
      noCryptoHoldings: "Sin criptos",
      addStocks: "Añadir acciones",
      refresh: "Actualizar",
    },
    // Holdings
    holdings: {
      title: "Cartera",
      subtitle: "Gestiona tu cartera de acciones",
      addHolding: "Añadir Posición",
      editHolding: "Editar Posición",
      addNewStock: "Añadir una nueva acción a tu cartera",
      updateDetails: "Actualizar los detalles de tu posición",
      stockSymbol: "Símbolo de la Acción",
      shares: "Acciones",
      buyPrice: "Precio de Compra",
      buyDate: "Fecha de Compra (opcional)",
      cancel: "Cancelar",
      save: "Guardar",
      update: "Actualizar",
      add: "Añadir",
      saving: "Guardando...",
      noHoldingsYet: "Sin posiciones aún",
      startBuilding: "Comienza a construir tu cartera añadiendo tu primera acción.",
      addFirstHolding: "Añadir Tu Primera Posición",
      currentPrice: "Precio Actual",
      marketValue: "Valor de Mercado",
      gainLoss: "Ganancia/Pérdida",
      edit: "Editar",
      delete: "Eliminar",
    },
    // Watchlist
    watchlist: {
      title: "Lista de Seguimiento",
      subtitle: "Sigue las acciones que te interesan",
      addStock: "Añadir Acción",
      addToWatchlist: "Añadir a la Lista",
      searchAndAdd: "Busca y añade una acción para seguir",
      cancel: "Cancelar",
      add: "Añadir",
      adding: "Añadiendo...",
      emptyTitle: "Tu lista de seguimiento está vacía",
      emptyDescription: "Añade acciones para seguir sus precios sin poseerlas.",
      addFirstStock: "Añadir Tu Primera Acción",
      addedOn: "Añadido el",
      volume: "Vol",
    },
    // Crypto
    crypto: {
      title: "Cripto",
      subtitle: "Gestiona tu cartera de criptomonedas",
      refresh: "Actualizar",
      cryptoValue: "Valor Cripto",
      gainLoss: "Ganancia/Pérdida",
      holdings: "Posiciones",
      watching: "Siguiendo",
      cryptocurrencies: "criptomonedas",
      inWatchlist: "en seguimiento",
      holdingsTab: "Posiciones",
      watchlistTab: "Seguimiento",
      marketTab: "Mercado",
      addHolding: "Añadir Posición",
      addCryptoHolding: "Añadir Posición Cripto",
      editCryptoHolding: "Editar Posición Cripto",
      searchAndAdd: "Busca y añade una criptomoneda",
      updateDetails: "Actualizar los detalles de tu posición",
      cryptocurrency: "Criptomoneda",
      amount: "Cantidad",
      buyPriceUSD: "Precio de Compra (USD)",
      buyDate: "Fecha de Compra (opcional)",
      cancel: "Cancelar",
      save: "Guardar",
      update: "Actualizar",
      add: "Añadir",
      saving: "Guardando...",
      noCryptoHoldings: "Sin posiciones cripto aún",
      startTracking: "Comienza a seguir tu cartera cripto añadiendo tu primera posición.",
      addFirstCrypto: "Añadir Tu Primera Cripto",
      currentPrice: "Precio Actual",
      marketValue: "Valor de Mercado",
      edit: "Editar",
      delete: "Eliminar",
      addToWatchlist: "Añadir a la Lista",
      searchCrypto: "Busca una criptomoneda para seguir",
      emptyWatchlist: "Lista de seguimiento vacía",
      emptyWatchlistDesc: "Añade criptomonedas para seguir sus precios.",
      topCryptocurrencies: "Top Criptomonedas",
      price: "Precio",
      change24h: "24h",
      marketCap: "Cap. de Mercado",
    },
    // Alerts
    alerts: {
      title: "Alertas de Precio",
      subtitle: "Recibe notificaciones cuando los precios alcancen tus objetivos",
      enableNotifications: "Activar Notificaciones",
      checkNow: "Verificar Ahora",
      createAlert: "Crear Alerta",
      notificationsEnabled: "Notificaciones activadas - serás alertado cuando se alcancen tus objetivos",
      active: "Activas",
      triggered: "Activadas",
      noActiveAlerts: "Sin alertas activas",
      createAlertsDesc: "Crea alertas para ser notificado cuando los precios alcancen tus objetivos.",
      createFirstAlert: "Crear Tu Primera Alerta",
      noTriggeredAlerts: "Sin alertas activadas",
      triggeredAlertsDesc: "Las alertas activadas aparecerán aquí.",
      createPriceAlert: "Crear Alerta de Precio",
      getNotified: "Recibe notificaciones cuando un activo alcance tu precio objetivo",
      assetType: "Tipo de Activo",
      stock: "Acción",
      searchStock: "Buscar Acción",
      searchCrypto: "Buscar Criptomoneda",
      condition: "Condición",
      priceAbove: "Precio sube por encima de",
      priceBelow: "Precio baja por debajo de",
      targetPrice: "Precio Objetivo (USD)",
      cancel: "Cancelar",
      create: "Crear Alerta",
      creating: "Creando...",
      target: "Objetivo",
      priceAtTrigger: "Precio al Activar",
      currentPrice: "Precio Actual",
      resetAlert: "Restablecer",
      triggeredOn: "Activada el",
      above: "Por encima",
      below: "Por debajo",
    },
    // Auth
    auth: {
      welcomeBack: "Bienvenido de nuevo",
      signInToPortfolio: "Inicia sesión en tu cartera",
      email: "Correo electrónico",
      password: "Contraseña",
      signIn: "Iniciar Sesión",
      signingIn: "Iniciando sesión...",
      noAccount: "¿No tienes cuenta?",
      createAccount: "Crear cuenta",
      createAnAccount: "Crear una cuenta",
      startTracking: "Comienza a seguir tus inversiones hoy",
      name: "Nombre",
      creatingAccount: "Creando cuenta...",
      alreadyHaveAccount: "¿Ya tienes cuenta?",
      signInLink: "Iniciar sesión",
    },
    // Common
    common: {
      loading: "Cargando...",
      error: "Error",
      success: "Éxito",
      search: "Buscar",
      save: "Guardar",
      cancel: "Cancelar",
      delete: "Eliminar",
      edit: "Editar",
      add: "Añadir",
      remove: "Quitar",
      confirm: "Confirmar",
      close: "Cerrar",
      yes: "Sí",
      no: "No",
    },
    // Settings
    settings: {
      title: "Configuración",
      subtitle: "Gestiona las preferencias de la aplicación",
      languageTitle: "Idioma",
      languageDescription: "Elige tu idioma preferido para la aplicación",
    },
  },
};

const languages = [
  { code: "en", name: "English", flag: "🇬🇧" },
  { code: "fr", name: "Français", flag: "🇫🇷" },
  { code: "de", name: "Deutsch", flag: "🇩🇪" },
  { code: "es", name: "Español", flag: "🇪🇸" },
];

const LanguageContext = createContext(null);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(
    localStorage.getItem("language") || "en"
  );

  useEffect(() => {
    localStorage.setItem("language", language);
  }, [language]);

  const t = (key) => {
    const keys = key.split(".");
    let value = translations[language];
    for (const k of keys) {
      value = value?.[k];
    }
    return value || key;
  };

  const changeLanguage = (lang) => {
    if (translations[lang]) {
      setLanguage(lang);
    }
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: changeLanguage, t, languages }}>
      {children}
    </LanguageContext.Provider>
  );
};
